baseURL = "https://dazzling-roentgen-3e71e9.netlify.app/"
title = "Christopher Gandrud ℈"
author = "Christopher Gandrud"
copyright = "© 2020, Christopher Gandrud"
paginate = 4
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "origin-hugo-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  description = "Christopher Gandrud's personal website"
  featured = true
  cssonly = false

  [params.socials]
    twitter = "https://twitter.com/ChrisGandrud"
    github = "https://github.com/christophergandrud"
    linkedin = "https://www.linkedin.com/in/christopher-gandrud-2b632936/"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe = true


